api/urls.py
from django.urls import path

from api.apps import ApiConfig
from api.views import AddLikeView, AllPosts, Post

app_name = ApiConfig.name

urlpatterns = [
    path("v1/posts/", AllPosts.as_view(), name="posts"),
    path("v1/post/<int:pk>/", Post.as_view(), name="post_retrieve"),
    path("v1/like_post/<int:pk>/", AddLikeView.as_view(), name="like_post"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from payments.views import stripe_webhook_view

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
    path("users/", include("users.urls", namespace="users")),
    path("payments/", include("payments.urls", namespace="payments")),
    path("api/", include("api.urls", namespace="api")),
    path("webhook/stripe/", stripe_webhook_view, name="stripe_webhook"),
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

payments/urls.py
from django.urls import path

from payments.apps import PaymentsConfig
from payments.views import CancelPayment, ConfirmPayment, SuccessPayment

app_name = PaymentsConfig.name

urlpatterns = [
    path("confirm/", ConfirmPayment.as_view(), name="confirm"),
    path("cancel/", CancelPayment.as_view(), name="cancel"),
    path("success/", SuccessPayment.as_view(), name="success"),
]

posts/urls.py
from django.urls import path

from posts import views
from posts.apps import PostsConfig

app_name = PostsConfig.name

urlpatterns = [
    path("", views.PostListView.as_view(), name="all_posts"),
    path("my_posts/", views.MyPost.as_view(), name="my_posts"),
    path("add_post/", views.PostCreateView.as_view(), name="add_post"),
    path("post/<int:pk>", views.PostDetailView.as_view(), name="post"),
    path("delete_post/<int:pk>", views.PostDeleteView.as_view(), name="delete_post"),
    path("liked_post/", views.LikedPosts.as_view(), name="liked_posts"),
]

payments/models.py
from django.db import models

from subscription.models import Subscription
from users.models import NULLABLE, User


class PaymentModel(models.Model):
    """Creating payments model"""

    payment_date = models.DateTimeField(
        auto_now_add=True, verbose_name="date of payment"
    )
    stripe_id = models.CharField(
        max_length=128, verbose_name="payment id on stripe", **NULLABLE
    )
    payment_status = models.BooleanField(default=False, verbose_name="payment's status")
    user = models.ForeignKey(
        to=User,
        on_delete=models.DO_NOTHING,
        related_name="user_payment",
        verbose_name="user_payment",
        **NULLABLE,
    )
    subscription = models.ForeignKey(
        to=Subscription, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return f"{self.payment_status}"

    class Meta:
        verbose_name = "payment"
        verbose_name_plural = "payments"

payments/forms.py
from django import forms

from payments.models import PaymentModel
from posts.forms import StyleFormMixin


class PaymentForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = PaymentModel
        fields = ("subscription",)

payments/views.py
from http import HTTPStatus

import stripe
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from config.settings import STRIPE_SECRET_KEY, STRIPE_WEBHOOK_KEY, DOMAIN_NAME
from payments.forms import PaymentForm
from payments.models import PaymentModel
from subscription.models import Subscription
from users.models import User

stripe.api_key = STRIPE_SECRET_KEY


class CancelPayment(TemplateView):
    """View for cancel payments"""

    template_name = "payments/cancel.html"


class SuccessPayment(TemplateView):
    """View for success payments"""

    template_name = "payments/success.html"


class ConfirmPayment(generic.CreateView):
    model = PaymentModel
    template_name = "payments/confirm_payment.html"
    form_class = PaymentForm
    success_url = reverse_lazy("posts:all_posts")

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        payment_instance = Subscription.objects.get(pk=int(form.data["subscription"]))
        super(ConfirmPayment, self).post(request, *args, **kwargs)
        price = payment_instance.stripe_price_id
        session = stripe.checkout.Session.create(
            success_url=DOMAIN_NAME + reverse("payments:success"),
            line_items=[{"price": price, "quantity": 1}],
            mode="payment",
            metadata={"payment_id": self.object.id},
        )
        return HttpResponseRedirect(session.url, status=HTTPStatus.SEE_OTHER)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ConfirmPayment, self).form_valid(form)


@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META["HTTP_STRIPE_SIGNATURE"]
    event = None
    try:
        event = stripe.Webhook.construct_event(payload, sig_header, STRIPE_WEBHOOK_KEY)
    except ValueError:
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError:
        return HttpResponse(status=400)
    if event["type"] == "checkout.session.completed":
        session = stripe.checkout.Session.retrieve(event["data"]["object"]["id"])

        fulfill_order(session)

    return HttpResponse(status=200)


def fulfill_order(session):
    payment_id = int(session.metadata.payment_id)
    payment = PaymentModel.objects.get(pk=payment_id)
    payment.payment_status = True
    payment.stripe_id = session.stripe_id
    payment.save()

    user = User.objects.get(pk=payment.user.pk)
    user.is_paid_subscribe = True
    user.save()

payments/templates/payments/cancel.html
{% extends 'posts/base.html' %}
{% block content %}
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header">
                            <h3 class="text-center font-weight-light my-4">Sorry, something went wrong.
                            </h3>
                        </div>
                         <div class="d-grid gap-2">
                              <button onclick="window.location.href='{% url 'payments:confirm' %}'"  class="btn active" role="button" data-bs-toggle="button" aria-pressed="true">
                                  Try again!
                              </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

payments/templates/payments/confirm_payment.html
{% extends 'posts/base.html'  %}
{% block content %}
    <style>
        .btn.btn-outline-light{
            background-color:#696969;
            color: #F8F8FF;
        }
    </style>
        <div class="col-5" >
            <div class='nav-item ml-auto'>
                <div class="card-header">
                    <h5> Please select a subscription and confirm the payment</h5>
                </div>
                <div class="card-body" >
                    <form method="post" >
                        {{ form.as_p }}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-light"> Confirm!</button>
                    </form>
                </div>
            </div>
        </div>
{% endblock content %}

payments/templates/payments/success.html
{% extends 'posts/base.html' %}
{% block content %}
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header">
                            <h3 class="text-center font-weight-light my-4">Thank you, you have successfully paid for
                              your subscription
                            </h3>
                        </div>
                        <div class="d-grid gap-2">
                              <button onclick="window.location.href='{% url 'posts:all_posts' %}'"  class="btn active" role="button" data-bs-toggle="button" aria-pressed="true">
                                  See all posts!
                              </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}