api/urls.py
from django.urls import path

from api.apps import ApiConfig
from api.views import AddLikeView, AllPosts, Post

app_name = ApiConfig.name

urlpatterns = [
    path("v1/posts/", AllPosts.as_view(), name="posts"),
    path("v1/post/<int:pk>/", Post.as_view(), name="post_retrieve"),
    path("v1/like_post/<int:pk>/", AddLikeView.as_view(), name="like_post"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from payments.views import stripe_webhook_view

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
    path("users/", include("users.urls", namespace="users")),
    path("payments/", include("payments.urls", namespace="payments")),
    path("api/", include("api.urls", namespace="api")),
    path("webhook/stripe/", stripe_webhook_view, name="stripe_webhook"),
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views
from users.apps import UsersConfig
from users.views import UserLogIn

app_name = UsersConfig.name


urlpatterns = [
    path("login/", UserLogIn.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout", kwargs={"next_page": "/"}),
    path("register/", views.UserRegisterView.as_view(), name="register"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("new_password/", views.generate_new_password, name="new_password"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models

NULLABLE = {"null": True, "blank": True}


class User(AbstractUser):
    """User's model"""

    number_validator = RegexValidator(
        regex=r"^\+\d{9,15}$",
        message='Phone number should start from "+" and consists of 9-15 digits',
    )

    username = None
    phone = models.CharField(
        max_length=15, verbose_name="phone", unique=True, validators=[number_validator]
    )
    email = models.EmailField(unique=True, verbose_name="email", **NULLABLE)
    city = models.CharField(max_length=135, verbose_name="city", **NULLABLE)
    avatar = models.ImageField(upload_to="users/", verbose_name="avatar", **NULLABLE)
    is_paid_subscribe = models.BooleanField(
        default=False, verbose_name=" paid subscription "
    )

    USERNAME_FIELD = "phone"
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)

from posts.forms import StyleFormMixin
from users.models import User


class UserLogInForm(StyleFormMixin, AuthenticationForm):
    """Stylization AuthenticationForm form"""

    pass


class UserForm(StyleFormMixin, UserCreationForm):
    """Form for model User"""

    class Meta:
        model = User
        fields = ("phone", "email", "password1", "password2")


class ProfileForm(StyleFormMixin, UserChangeForm):
    """Form for user's profile"""

    class Meta:
        model = User
        fields = ("phone", "email", "password", "city", "avatar")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password"].widget = forms.HiddenInput()

users/views.py
import secrets
import string

from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from config.settings import EMAIL_HOST_USER
from users.forms import ProfileForm, UserForm, UserLogInForm
from users.models import User


class UserLogIn(LoginView):
    """Add stylized form"""

    form_class = UserLogInForm


class UserRegisterView(generic.CreateView):
    """Create user views"""

    model = User
    form_class = UserForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        send_mail(
            subject="Successful registration",
            message="Hello, congratulations on your successful registration",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


class ProfileView(generic.UpdateView):
    """Views for updating user's profile"""

    model = User
    form_class = ProfileForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user


@login_required
def generate_new_password(request):
    """New  random password generation"""

    data = string.ascii_letters + string.digits + string.punctuation
    new_password = "".join(secrets.choice(data) for _ in range(12))
    request.user.set_password(new_password)
    send_mail(
        subject="New password",
        message=f"Hello, your new password: {new_password}",
        from_email=EMAIL_HOST_USER,
        recipient_list=[request.user.email],
    )
    request.user.save()
    return redirect(reverse("users:login"))

users/templates/users/login.html
{% extends 'posts/base.html' %}
{% block content %}

    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h5> Authorisation </h5>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-light"> Log in</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends 'posts/base.html'  %}
{% block content %}
<style>
    .btn.btn-outline-light{
        background-color:#696969;
        color: #F8F8FF;
    }
</style>
            <div class="col-5" >
                <div class='nav-item ml-auto'>
                    <div class="card-header">
                        <h5> User registration </h5>
                    </div>
                    <div class="card-body" >
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-outline-light"> Sign up!</button>
                        </form>
                    </div>
                </div>
            </div>
{% endblock content %}

users/templates/users/user_form.html
{% extends 'posts/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h5> My profile </h5>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-outline-light"> Save </button>
                        </form>
                    </div>
                    <div class="card_footer">
                        <a href="{% url 'users:new_password' %}" class="btn btn-outline-light"> Generate a new password </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}