api/urls.py
from django.urls import path

from api.apps import ApiConfig
from api.views import AddLikeView, AllPosts, Post

app_name = ApiConfig.name

urlpatterns = [
    path("v1/posts/", AllPosts.as_view(), name="posts"),
    path("v1/post/<int:pk>/", Post.as_view(), name="post_retrieve"),
    path("v1/like_post/<int:pk>/", AddLikeView.as_view(), name="like_post"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from payments.views import stripe_webhook_view

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
    path("users/", include("users.urls", namespace="users")),
    path("payments/", include("payments.urls", namespace="payments")),
    path("api/", include("api.urls", namespace="api")),
    path("webhook/stripe/", stripe_webhook_view, name="stripe_webhook"),
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

posts/urls.py
from django.urls import path

from posts import views
from posts.apps import PostsConfig

app_name = PostsConfig.name

urlpatterns = [
    path("", views.PostListView.as_view(), name="all_posts"),
    path("my_posts/", views.MyPost.as_view(), name="my_posts"),
    path("add_post/", views.PostCreateView.as_view(), name="add_post"),
    path("post/<int:pk>", views.PostDetailView.as_view(), name="post"),
    path("delete_post/<int:pk>", views.PostDeleteView.as_view(), name="delete_post"),
    path("liked_post/", views.LikedPosts.as_view(), name="liked_posts"),
]

posts/models.py
from django.db import models

import users.models
from config.settings import AUTH_USER_MODEL
from users.models import NULLABLE


class PostModel(models.Model):
    """Post's model"""

    title = models.CharField(max_length=255, verbose_name="title")
    description = models.TextField(verbose_name="description", **NULLABLE)
    post_owner = models.ForeignKey(
        to=AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="post_owner",
        verbose_name="post_owner",
        null=True,
    )
    is_free = models.BooleanField(default=False, verbose_name="is free?")
    image = models.ImageField(upload_to="posts/", verbose_name="image", **NULLABLE)
    publish_date = models.DateField(auto_now_add=True, verbose_name="published date")
    views_count = models.IntegerField(default=0, verbose_name="views count")
    likes = models.ManyToManyField(
        to=users.models.User, related_name="likes", blank=True
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "post"
        verbose_name_plural = "posts"

posts/forms.py
from django import forms

from posts.models import PostModel


class StyleFormMixin:
    """Form stylization"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class PostModelForm(StyleFormMixin, forms.ModelForm):
    """Form for model PostModel"""

    class Meta:
        model = PostModel
        fields = ("title", "description", "is_free", "image")

posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from posts.forms import PostModelForm
from posts.models import PostModel


class PostListView(generic.ListView):
    """List of all posts"""

    model = PostModel
    ordering = ("publish_date",)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated and self.request.user.is_paid_subscribe:
            queryset = PostModel.objects.all()
        else:
            queryset = PostModel.objects.filter(is_free=True)

        queryset = queryset.order_by("-publish_date")
        context["object_list"] = queryset
        return context


class MyPost(LoginRequiredMixin, generic.ListView):
    """List of all posts"""

    model = PostModel

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        queryset = PostModel.objects.filter(post_owner=self.request.user).all()
        queryset = queryset.order_by("-publish_date")
        context["object_list"] = queryset
        return context


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    """Create a post"""

    model = PostModel
    form_class = PostModelForm
    success_url = reverse_lazy("posts:all_posts")

    def form_valid(self, form):
        self.object = form.save()
        self.object.post_owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class PostDetailView(generic.DetailView):
    """Getting selected post"""

    model = PostModel

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["object_list"] = PostModel.objects.filter(pk=self.object.pk)
        else:
            context["object_list"] = PostModel.objects.filter(
                pk=self.object.pk, is_free=True
            )
        self.object.views_count += 1
        self.object.save()
        return context


class PostDeleteView(LoginRequiredMixin, generic.DeleteView):
    """Delete selected post"""

    model = PostModel
    success_url = reverse_lazy("posts:all_posts")


class LikedPosts(generic.ListView):
    """All liked posts"""

    model = PostModel

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        queryset = PostModel.objects.filter(likes=self.request.user)
        queryset = queryset.order_by("-publish_date")
        context["object_list"] = queryset
        return context

posts/templates/posts/postmodel_confirm_delete.html
{% extends 'posts/base.html' %}
{% block content %}
    <div class="col-6">
        <div class="card mb-6 box-shadow">
            <div class="card-body">
              <form method="post">
                {% csrf_token %}
                <p>Delete: {{ object.title }} ?</p>
                <button type="submit" class=" btn btn-outline-light">Confirm deletion</button>
                <a href="{% url 'posts:my_posts' %}" type="button" class="btn btn-outline-light">Cancel</a>
              </form>
            </div>
        </div>
    </div>
{% endblock content %}

posts/templates/posts/postmodel_detail.html
{% extends 'posts/base.html' %}
{% block content %}
{% load static %}
{% for  post in object_list %}
    <div class="col">
            <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('unsplash-photo-2.jpg');">
                <div class="card-header">
                    <ul class="nav-item ml-auto">
                        <li class="d-grid gap-2 d-md-flex justify-content-center ">
                            <h3 class="d-grid gap-2 d-md-flex justify-content-md-start">{{ post.title }}</h3>
                        </li>
                        <li class="d-grid gap-2 d-md-flex justify-content-start">
                            <a href="{% url 'posts:all_posts' %}" class="py-4 btn " title="Go back" data-bs-toggle="tooltip" >
                                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-left-square" viewBox="0 0 16 16">
                                  <path fill-rule="evenodd" d="M15 2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1zM0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm11.5 5.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z"/>
                                </svg>
                            </a>
                            {% if user == post.post_owner %}
                             <a href="{% url 'posts:delete_post' post.pk %}" class="py-4 btn" title="Delete" data-bs-toggle="tooltip">
                               <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                  <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                </svg>
                            </a>
                         {% endif %}
                        </li>
                        <li class="d-grid gap-2 d-md-flex justify-content-end">
                            <h6 class="nav-item py-6 ">Author: {{ post.post_owner }}</h6>
                        </li>
                        <li class="d-grid gap-2 d-md-flex justify-content-end">
                            <h6 class="nav-item py-6 ">Public date: {{ post.publish_date }}</h6>
                        </li>
                    </ul>
                </div>
                <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                    <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">{{post.description }}</h3>
                    <ul class="nav-item ml-auto">
                        <li class="d-grid gap-3 d-md-flex justify-content-md-end">
                            {% if user.is_authenticated %}
                                <a id="likeBtn_{{ post.pk }}" class="likeBtn py-3 btn" data-post-id="{{ post.pk }}">
                                {% if user in post.likes.all %}
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
                                    </svg>
                                {% else %}
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                                        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.920 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                                    </svg>
                                {% endif %}
                                <span class="likesCount" id="likesCount_{{ post.pk }}">{{ post.likes.count }}</span>
                                </a>
                                <script>
                                    document.getElementById('likeBtn_{{ post.pk }}').addEventListener('click', function() {
                                        var post_id = this.getAttribute('data-post-id');
                                        var csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

                                        fetch(`api/v1/like_post/${post_id}/`, {
                                            method: 'POST',
                                            headers: {
                                                'Content-Type': 'application/json',
                                                'X-CSRFToken': csrftoken,
                                            },
                                        })
                                        .then(response => response.json())
                                        .then(data => {
                                            var likesCountElement = document.getElementById('likesCount_' + post_id);
                                            likesCountElement.innerText = data.likes_count;

                                        });
                                    });
                                </script>
                            {% endif %}

                            <a class="py-3 btn " title="Views" data-bs-toggle="tooltip">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                  <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                                  <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/>
                                </svg>
                                <small>{{ post.views_count }}</small>
                            </a>

                        </li>
                    </ul>
                </div>
            </div>
    </div>
{% endfor %}
{% endblock content %}

posts/templates/posts/postmodel_form.html
{% extends 'posts/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-outline-light">
                                {% if object %}
                                    Save changes
                                {% else %}
                                    Publish
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

posts/templates/posts/postmodel_list.html
{% extends 'posts/base.html' %}
{% block content %}
{% for post in object_list %}
    <div class="col">
        <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg">
            <div class="card-header">
                <ul class="nav-item ml-auto">
                    <li class="d-grid gap-2 d-md-flex justify-content-center ">
                        <h3 class="d-grid gap-2 d-md-flex justify-content-md-center">{{ post.title }}</h3>
                    </li>
                     <li class="d-grid gap-2 d-md-flex justify-content-start">
                        <a href="{% url 'posts:post' post.pk %}" class="py-3 btn" title="Read the full post" data-bs-toggle="tooltip">
                           <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-three-dots" viewBox="0 0 16 16">
                              <path d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3"/>
                            </svg>
                        </a>
                         {% if user == post.post_owner %}
                         <a href="{% url 'posts:delete_post' post.pk %}" class="py-3 btn" title="Delete" data-bs-toggle="tooltip">
                           <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                              <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                              <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                            </svg>
                        </a>
                         {% endif %}
                    </li>

                    <li class="d-grid gap-2 d-md-flex justify-content-end">
                        <h6 class="nav-item py-6 ">Author: {{ post.post_owner }}</h6>
                    </li>
                    <li class="d-grid gap-2 d-md-flex justify-content-end">
                        <h6 class="nav-item py-6 ">Public date: {{ post.publish_date }}</h6>
                    </li>
                </ul>
            </div>
            <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">{{post.description|truncatechars:60  }}</h3>
                <ul class="nav-item ml-auto">
                    <li class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <li class="d-grid gap-3 d-md-flex justify-content-md-end">
                            {% if user.is_paid_subscribe %}
                               <a id="likeBtn_{{ post.pk }}" class="likeBtn py-3 btn" data-post-id="{{ post.pk }}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="{% if user in post.likes.all %}bi bi-heart-fill liked{% else %}bi bi-heart not-liked{% endif %}" viewBox="0 0 16 16">
                                        {% if user in post.likes.all %}
                                            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
                                        {% else %}
                                            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.920 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                                        {% endif %}
                                    </svg>
                                    <span class="likesCount" id="likesCount_{{ post.pk }}">{{ post.likes.count }}</span>
                                </a>
                                <script>
                                    document.getElementById('likeBtn_{{ post.pk }}').addEventListener('click', function() {
                                        var post_id = this.getAttribute('data-post-id');
                                        var csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
                                        var likeIcon = this.querySelector('svg');

                                        fetch(`/api/v1/like_post/${post_id}/`, {
                                            method: 'POST',
                                            headers: {
                                                'Content-Type': 'application/json',
                                                'X-CSRFToken': csrftoken,
                                            },
                                        })
                                        .then(response => response.json())
                                        .then(data => {
                                            var likesCountElement = document.getElementById('likesCount_' + post_id);
                                            likesCountElement.innerText = data.likes_count;

                                            likeIcon.classList.toggle('liked', data.liked);
                                            likeIcon.classList.toggle('not-liked', !data.liked);
                                        });
                                    });
                                </script>
                            {% endif %}
                            <a class="py-3 btn" title="Views" data-bs-toggle="tooltip">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                  <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                                  <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/>
                                </svg>
                                <small>{{ post.views_count }}</small>
                            </a>
                        </li>
                </ul>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}